# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.ssh.forward_agent = true

  # VirtualBox
  config.vm.provider :virtualbox do |v|
    v.cpus   = 2
    v.memory = 4096
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--ioapic", "on"]
  end

  # Rocky 8
  config.vm.define "rocky8" do |rocky8|
    rocky8.vm.box_check_update = false
    rocky8.vm.box              = "generic/rocky8"
    rocky8.vm.hostname         = "rocky8.heartbeat.lan"
    rocky8.vm.network :forwarded_port, guest: 22, host: 10822, id: "ssh"

    # update packages
    config.vm.provision "shell", inline: <<-SHELL
      sudo dnf update -y
    SHELL
  end

end
