# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.ssh.forward_agent = true

  # VirtualBox
  config.vm.provider :virtualbox do |v|
    v.cpus   = 2
    v.memory = 4096
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--ioapic", "on"]
  end

  # Rocky 9
  config.vm.define "rocky9" do |rocky9|
    rocky9.vm.box_check_update = false
    rocky9.vm.box              = "generic/rocky9"
    rocky9.vm.hostname         = "rocky9.heartbeat.lan"
    rocky9.vm.network :forwarded_port, guest: 22, host: 10922, id: "ssh"

    # update packages
    config.vm.provision "shell", inline: <<-SHELL
      sudo dnf update -y
    SHELL
  end

end
