# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.ssh.forward_agent = true

  # VirtualBox
  config.vm.provider :virtualbox do |v|
    v.cpus   = 2
    v.memory = 4096
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--ioapic", "on"]
  end

  # CentOS 6 (default Toptal OS)
  config.vm.define "centos6" do |centos6|
    centos6.vm.box_check_update = false
    centos6.vm.box              = "centos/6"
    centos6.vm.hostname         = "centos6.heartbeat.lan"
    centos6.vm.network :forwarded_port, guest: 22, host: 10622, id: "ssh"

    # update packages
    config.vm.provision "shell", inline: <<-SHELL
      sudo sed -i -e 's/^mirrorlist/#mirrorlist/g' -e 's|^#baseurl=http://mirror.centos.org/centos/$releasever/|baseurl=https://vault.centos.org/6.10/|g' /etc/yum.repos.d/CentOS*.repo
      sudo yum -y install https://archives.fedoraproject.org/pub/archive/epel/6/x86_64/epel-release-6-8.noarch.rpm
      sudo yum update -y
    SHELL
  end

end
