FROM jsosic/rpmbuilder:el7
RUN sudo yum -y install https://dl.iuscommunity.org/pub/ius/stable/CentOS/7/x86_64/ius-release-1.0-14.ius.centos7.noarch.rpm \
 && sudo yum -y update \
 && sudo yum clean all
